name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Build with Gradle
        id: build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload common build artifacts
        uses: actions/upload-artifact@v3
        if: steps.build.outcome == 'success'
        with:
          name: Common
          path: common/build/libs/*.jar

      - name: Upload Fabric build artifacts
        uses: actions/upload-artifact@v3
        if: steps.build.outcome == 'success'
        with:
          name: Fabric
          path: fabric/build/libs/*.jar

      - name: Upload Forge build artifacts
        uses: actions/upload-artifact@v3
        if: steps.build.outcome == 'success'
        with:
          name: Forge
          path: forge/build/libs/*.jar
